program ORBIS;

uses
  System.StartUpCopy,
  App.Abstractions in 'AppCore\App.Abstractions.pas',
  App.Config in 'AppCore\App.Config.pas',
  App.Core in 'AppCore\App.Core.pas',
  App.Globals in 'AppCore\App.Globals.pas',
  App.HandlerCore in 'AppCore\App.HandlerCore.pas',
  App.IHandlerCore in 'AppCore\App.IHandlerCore.pas',
  App.Log in 'AppCore\App.Log.pas',
  App.Meta in 'AppCore\App.Meta.pas',
  App.Notifyer in 'AppCore\App.Notifyer.pas',
  App.Packet in 'AppCore\App.Packet.pas',
  App.Paths in 'AppCore\App.Paths.pas',
  App.Types in 'AppCore\App.Types.pas',
  WebServer.DataControl in 'AppCore\WebCore\WebServer.DataControl.pas',
  WebServer.HTTPConnectedClient in 'AppCore\WebCore\WebServer.HTTPConnectedClient.pas',
  WebServer.HTTPCore in 'AppCore\WebCore\WebServer.HTTPCore.pas',
  WebServer.HTTPServer in 'AppCore\WebCore\WebServer.HTTPServer.pas',
  WebServer.HTTPTypes in 'AppCore\WebCore\WebServer.HTTPTypes.pas',
  WebServer.SourceData in 'AppCore\WebCore\WebServer.SourceData.pas',
  Wallet.Core in 'AppCore\WalletCore\Wallet.Core.pas',
  Wallet.FileHandler in 'AppCore\WalletCore\Wallet.FileHandler.pas',
  Wallet.Types in 'AppCore\WalletCore\Wallet.Types.pas',
  QR.CORE in 'AppCore\Utilities\QR.CORE.pas',
  UHandlerResultComandLineParse in 'AppCore\UICore\UHandlerResultComandLineParse.pas',
  Net.AbstractClient in 'AppCore\NetCore\Net.AbstractClient.pas',
  Net.Client in 'AppCore\NetCore\Net.Client.pas',
  Net.ConnectedClient in 'AppCore\NetCore\Net.ConnectedClient.pas',
  Net.Core in 'AppCore\NetCore\Net.Core.pas',
  Net.IClient in 'AppCore\NetCore\Net.IClient.pas',
  Net.Server in 'AppCore\NetCore\Net.Server.pas',
  Net.Types in 'AppCore\NetCore\Net.Types.pas',
  Crypto.AlphabetBase58 in 'AppCore\CryptoCore\Crypto.AlphabetBase58.pas',
  Crypto.Base58 in 'AppCore\CryptoCore\Crypto.Base58.pas',
  Crypto.BinConverter in 'AppCore\CryptoCore\Crypto.BinConverter.pas',
  Crypto.BIP39 in 'AppCore\CryptoCore\Crypto.BIP39.pas',
  Crypto.Data in 'AppCore\CryptoCore\Crypto.Data.pas',
  Crypto.Encoding in 'AppCore\CryptoCore\Crypto.Encoding.pas',
  Crypto.RSA in 'AppCore\CryptoCore\Crypto.RSA.pas',
  CryptoEntity in 'AppCore\CryptoCore\CryptoEntity.pas',
  RSA.cEncrypt in 'AppCore\CryptoCore\RSA.cEncrypt.pas',
  RSA.cHash in 'AppCore\CryptoCore\RSA.cHash.pas',
  RSA.cHugeInt in 'AppCore\CryptoCore\RSA.cHugeInt.pas',
  RSA.cRandom in 'AppCore\CryptoCore\RSA.cRandom.pas',
  RSA.main in 'AppCore\CryptoCore\RSA.main.pas',
  Unit_cryptography in 'AppCore\CryptoCore\Unit_cryptography.pas',
  BlockChain.Account in 'AppCore\BlockChain\BlockChain.Account.pas',
  BlockChain.BaseBlock in 'AppCore\BlockChain\BlockChain.BaseBlock.pas',
  BlockChain.BaseChain in 'AppCore\BlockChain\BlockChain.BaseChain.pas',
  BlockChain.Commission in 'AppCore\BlockChain\BlockChain.Commission.pas',
  BlockChain.Core in 'AppCore\BlockChain\BlockChain.Core.pas',
  BlockChain.FastIndex.Account in 'AppCore\BlockChain\BlockChain.FastIndex.Account.pas',
  BlockChain.FastIndex.Token in 'AppCore\BlockChain\BlockChain.FastIndex.Token.pas',
  BlockChain.FastIndex.Transfer in 'AppCore\BlockChain\BlockChain.FastIndex.Transfer.pas',
  BlockChain.FileHandler in 'AppCore\BlockChain\BlockChain.FileHandler.pas',
  BlockChain.Inquiries in 'AppCore\BlockChain\BlockChain.Inquiries.pas',
  BlockChain.MainChain in 'AppCore\BlockChain\BlockChain.MainChain.pas',
  BlockChain.Mining in 'AppCore\BlockChain\BlockChain.Mining.pas',
  BlockChain.MultiSign in 'AppCore\BlockChain\BlockChain.MultiSign.pas',
  BlockChain.Tokens in 'AppCore\BlockChain\BlockChain.Tokens.pas',
  BlockChain.Transfer in 'AppCore\BlockChain\BlockChain.Transfer.pas',
  BlockChain.Types in 'AppCore\BlockChain\BlockChain.Types.pas',
  BlockChain.VoteRequest in 'AppCore\BlockChain\BlockChain.VoteRequest.pas',
  BlockChain.VotingResults in 'AppCore\BlockChain\BlockChain.VotingResults.pas',
  BlockChain.RegisteredServices in 'AppCore\BlockChain\BlockChain.RegisteredServices.pas',
  WebServer.Abstractions in 'AppCore\WebCore\WebServer.Abstractions.pas',
  UI.Animated in 'AppCore\UICore\UI.Animated.pas',
  UI.Abstractions in 'AppCore\UICore\UI.Abstractions.pas',
  UI.CommandLineParser in 'AppCore\UICore\UI.CommandLineParser.pas',
  UI.ConsoleUI in 'AppCore\UICore\UI.ConsoleUI.pas',
  UI.GUI.FormsConrol in 'AppCore\UICore\UI.GUI.FormsConrol.pas',
  UI.GUI in 'AppCore\UICore\UI.GUI.pas',
  UI.GUI.Types in 'AppCore\UICore\UI.GUI.Types.pas',
  UI.ParserCommand in 'AppCore\UICore\UI.ParserCommand.pas',
  UI.Types in 'AppCore\UICore\UI.Types.pas',
  FMX.Forms,
  BlockChain.Service in 'AppCore\BlockChain\BlockChain.Service.pas',
  BlockChain.ServiceResult in 'AppCore\BlockChain\BlockChain.ServiceResult.pas',
  Updater.Core in 'AppCore\Updater\Updater.Core.pas',
  Translate.Core in 'AppCore\Translate\Translate.Core.pas',
  DGUI.ConfirmOM in 'AppCore\UICore\DesktopForms\DGUI.ConfirmOM.pas' {ConfirmOMForm},
  DGUI.ConfirmTransaction in 'AppCore\UICore\DesktopForms\DGUI.ConfirmTransaction.pas' {ConfirmTransForm},
  DGUI.Form.Base in 'AppCore\UICore\DesktopForms\DGUI.Form.Base.pas' {BaseForm},
  DGUI.Form.CreatePass in 'AppCore\UICore\DesktopForms\DGUI.Form.CreatePass.pas' {CreatePassForm},
  DGUI.Form.CreateToken in 'AppCore\UICore\DesktopForms\DGUI.Form.CreateToken.pas' {CreateTokenForm},
  DGUI.Form.EnterCryptoKeys in 'AppCore\UICore\DesktopForms\DGUI.Form.EnterCryptoKeys.pas' {EnterWords},
  DGUI.Form.FileCryptocontainer in 'AppCore\UICore\DesktopForms\DGUI.Form.FileCryptocontainer.pas' {FileCryptocontainerForm},
  DGUI.Form.GenCryptoKeys in 'AppCore\UICore\DesktopForms\DGUI.Form.GenCryptoKeys.pas' {GenCryptoKeysForm},
  DGUI.Form.LogIn in 'AppCore\UICore\DesktopForms\DGUI.Form.LogIn.pas' {LogInForm},
  DGUI.Form.MyAddress in 'AppCore\UICore\DesktopForms\DGUI.Form.MyAddress.pas' {MyAddressForm},
  DGUI.Form.NewTransaction in 'AppCore\UICore\DesktopForms\DGUI.Form.NewTransaction.pas' {NewTransactionForm},
  DGUI.Form.Progress in 'AppCore\UICore\DesktopForms\DGUI.Form.Progress.pas' {ProgressForm},
  DGUI.Form.RegCryptocontainer in 'AppCore\UICore\DesktopForms\DGUI.Form.RegCryptocontainer.pas' {RegCryptocontainerForm},
  DGUI.Form.Registration in 'AppCore\UICore\DesktopForms\DGUI.Form.Registration.pas' {RegistrationForm},
  DGUI.Form.RelogConfirm in 'AppCore\UICore\DesktopForms\DGUI.Form.RelogConfirm.pas' {RelogConfirmForm},
  DGUI.Form.ResCryptocontainer in 'AppCore\UICore\DesktopForms\DGUI.Form.ResCryptocontainer.pas' {ResCryptocontainerForm},
  DGUI.Form.Resources in 'AppCore\UICore\DesktopForms\DGUI.Form.Resources.pas' {ResourcesForm},
  DGUI.Form.TransactionInfo in 'AppCore\UICore\DesktopForms\DGUI.Form.TransactionInfo.pas' {TransactionInfoForm},
  DGUI.Form.Transactions in 'AppCore\UICore\DesktopForms\DGUI.Form.Transactions.pas' {TransactionsForm},
  DGUI.Form.Verification in 'AppCore\UICore\DesktopForms\DGUI.Form.Verification.pas' {VerificationForm},
  DGUI.Form.Waiting in 'AppCore\UICore\DesktopForms\DGUI.Form.Waiting.pas' {WaitingForm},
  DGUI.Frame.Splash in 'AppCore\UICore\DesktopForms\DGUI.Frame.Splash.pas' {SplashFrame: TFrame},
  DGUI.Toast.Windows in 'AppCore\UICore\DesktopForms\DGUI.Toast.Windows.pas' {ToastForm},
  BlockChain.FastIndex.RegistredService in 'AppCore\BlockChain\BlockChain.FastIndex.RegistredService.pas',
  BlockChain.FastIndex.Service in 'AppCore\BlockChain\BlockChain.FastIndex.Service.pas',
  App.Tools in 'AppCore\App.Tools.pas',
  Consensus2.Core in 'AppCore\Consensus\Consensus2.Core.pas',
  Consensus.Logic in 'AppCore\Consensus\Consensus.Logic.pas',
  Consensus.Types in 'AppCore\Consensus\Consensus.Types.pas',
  BlockChain.Mined in 'AppCore\BlockChain\BlockChain.Mined.pas',
  App.FileLocker in 'AppCore\App.FileLocker.pas';

{$APPTYPE GUI}
{$R *.res}

begin
{$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
{$ENDIF}
  AppCore := TAppCore.Create;
  AppCore.DoRun;
end.
